# Generated by Django 4.1.4 on 2023-01-30 22:19

import collection.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0002_collectible_universum_remove_collection_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='collection',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='historicalcollection',
            name='creator',
        ),
        migrations.AddField(
            model_name='collectible',
            name='collections',
            field=models.ManyToManyField(related_name='collectibles', related_query_name='collectible', to='collection.collection'),
        ),
        migrations.AddField(
            model_name='collectible',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='collectible',
            name='display_name',
            field=models.CharField(default='Collectible', max_length=200),
        ),
        migrations.AddField(
            model_name='collectible',
            name='slug',
            field=models.CharField(default='1-collectible', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectible',
            name='unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='universum',
            name='short_name',
            field=models.CharField(default='1-uni', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(default=collection.models.get_foster_collector, on_delete=models.SET(collection.models.get_foster_collector), related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, default=collection.models.get_foster_collector, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CreatorCompany',
            fields=[
                ('creator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collection.creator')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('collection.creator',),
        ),
        migrations.CreateModel(
            name='CreatorPerson',
            fields=[
                ('creator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collection.creator')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('middle_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('nickname', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('collection.creator',),
        ),
        migrations.CreateModel(
            name='UniversumType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200, unique=True)),
                ('universum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='collection.universum')),
            ],
        ),
        migrations.CreateModel(
            name='UniversumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200, unique=True)),
                ('universum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='collection.universum')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCollectible',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('display_name', models.CharField(default='Collectible', max_length=200)),
                ('slug', models.CharField(db_index=True, max_length=200)),
                ('unique', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, default=collection.models.get_foster_creator, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collection.creator')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical collectible',
                'verbose_name_plural': 'historical collectibles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='collectible',
            name='categories',
            field=models.ManyToManyField(related_name='collectibles', related_query_name='collectible', to='collection.universumcategory'),
        ),
        migrations.AddField(
            model_name='collectible',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=models.SET(collection.models.get_foster_creator), related_name='collectibles', to='collection.creator'),
        ),
        migrations.AddField(
            model_name='collectible',
            name='types',
            field=models.ManyToManyField(related_name='collectibles', related_query_name='collectible', to='collection.universumtype'),
        ),
        migrations.AlterField(
            model_name='universum',
            name='creator',
            field=models.ForeignKey(on_delete=models.SET(collection.models.get_foster_creator), related_name='universums', to='collection.creator'),
        ),
    ]
