# Generated by Django 4.1.4 on 2023-01-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_creator_remove_collection_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorperson',
            name='nickname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
