# Generated by Django 4.1.4 on 2023-02-04 10:32

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_creatorperson_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='icon_height',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='collection',
            name='icon_width',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='icon_height',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='icon_width',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='collectible',
            name='creator',
            field=models.ForeignKey(default=collection.models.get_foster_creator, on_delete=models.SET(collection.models.get_foster_creator), related_name='collectibles', to='collection.creator'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='icon',
            field=models.ImageField(height_field='icon_height', upload_to='collection_icons', width_field='icon_width'),
        ),
    ]
