# Generated by Django 4.1.4 on 2023-02-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_collection_icon_height_collection_icon_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universum',
            name='icon_height',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='universum',
            name='icon_width',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='universum',
            name='icon',
            field=models.ImageField(height_field='icon_height', upload_to='universum_icons', width_field='icon_width'),
        ),
    ]
